#!/usr/bin/perl

use v5.14;
use integer;

my %s = (
	'\\'=> '\\\\',
	"\t"=> '\t',
	'"' => '\"',
);

sub process {
	my $name = shift;
	open IN, '<', "$name.in";
	open OUT, '>', "$name.inc";
	my $sect;
	sub nextsect {
		print OUT ";\n" if $sect ne '';
		$sect = shift;
		print OUT "const char $name$sect"."[] =\n" if $sect ne '';
	}
	while (<IN>) {
		chomp;
		if (/^=([0-9]+)$/) {
			nextsect($1);
		} elsif ($sect ne '') {
			s/([\\\t"])/$s{$1}/ge;
			print OUT "\"$_\\n\"\n";
		}
	}
	nextsect('');
	close IN;
	close OUT;
}

process('preamble');
